---
title: "Lab 3"
author: "Kipras Varkala"
date: "2/7/2022"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)

library(tidyverse)
library(gapminder)
library(dplyr)
```

## Exercises

### Exercise 1: Basic dplyr

#### 1.1

```{r filtering}
gapdat <- gapminder

countries <- c("Kuwait","Japan","Ireland")

gapdat %>%
  filter(country %in% countries, 
         year >= 1970 & year <= 1979) %>%
  print()
```

#### 1.2

```{r selecting}
gapdat %>%
  filter(country %in% countries, 
         year >= 1970 & year <= 1979) %>%
  select(country, gdpPercap) %>%
  print()
```

#### 1.3

```{r selecting again}
Rwanda <-  
  gapdat %>%
  arrange(year) %>%
  group_by(country) %>%
  mutate(
    lifeExp_change = lifeExp - lag(lifeExp)
  ) %>%
  filter(lifeExp_change < 0) %>%
  ungroup() %>%
  filter(lifeExp_change == min(lifeExp_change)) %>%
  print()
```

#### 1.4

```{r filtering again}
gapdat %>%
  group_by(country) %>%
  mutate(
    maxGDP_per_capita = gdpPercap,
  ) %>%
  filter(maxGDP_per_capita == max(maxGDP_per_capita)) %>%
  select(country, maxGDP_per_capita) %>%
  print()
```

#### 1.5

```{r scatterplot}
gapdat %>%
  filter(country %in% "Canada") %>%
  ggplot() +
  aes(x = lifeExp, y = log(gdpPercap)) + 
  geom_point() 
```

### Excerise 2: Explore two variables with dplyr and ggplot2

#### 2.1

```{r exploring continuous variables}
#loading data
cars <- mtcars

#sub-setting only two variables
carsSubCont <- 
  cars %>%
  select(
    mpg,
    hp,
  ) %>%
  na.omit(mpg, hp)


#getting means, standard deviations, and ranges of both variables
carsSubCont %>%
 summarize(
    across(
      1:2,
      list(
        mean,
        median,
        sd
      )
    )
  ) %>%
  transmute(
    mpg_mean = mpg_1,
    mpg_median = mpg_2,
    mpg_sd = mpg_3,
    hp_mean = hp_1,
    hp_median = hp_2,
    hp_sd = hp_3
  )

#scatterplot of the variables
carsSubCont %>%
  ggplot() +
  aes(x = mpg, y = hp) + 
  geom_point() +
  labs(
    x="Miles Per Gallon (mpg)", 
    y="Horsepower (hp)"
  )
```

#### 2.2

```{r exploring mixed variables}
cars$cyl <- as.character(cars$cyl)

#sub-setting only two variables
carsSubCat <- cars %>% 
  group_by(cyl) %>%
  select(
    cyl,
    hp,
  ) %>%
  na.omit(cyl, hp)

#descriptive statistics by cylinders
carsSubCat %>%
  summarize(
    n = length(cyl),
    mean = mean(hp),
    median = median(hp),
    sd = sd(hp)
  ) 

#scatterplot of the variables
carsSubCat %>%
  ggplot() +
  aes(
    x = hp, 
    y = cyl, 
    color = cyl,
    fill = cyl) + 
  geom_point() +
  geom_jitter(height = 0,
              width = .05) +
   geom_boxplot(color = "black",
                alpha = .3) +
    ggdist::stat_slab(height = .3,
                    color = "black",
                    size = .2,
                    alpha = .3,
                    position = position_nudge(y = .5)) +
  labs(
    x="Horsepower (hp)", 
    y="Number of Cylinders (cyl)"
  )
```

### Buh Buh Buh Bonus O'Clock

```{r Bonus Exercise: Recycling}
filter(gapminder, country == c("Rwanda", "Afghanistan"))
```

The issue is that half of the data is lost when having the filter function look for these countries serially. Instead,
using the %in% operator looks for whether anything that matches within the vector. 

Below is the adjusted code.

```{r adjusted code}
filter(gapminder, country %in% c("Rwanda", "Afghanistan"))
```